version: '3'

services:

    # Database Storage
    mysql:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile.mysql
        image: mysql-stage:1
        container_name: database-sample-stage
        volumes: 
            - datasql:/var/lib/mysql
        networks:
            - staging
        ports:
            # HostPort:ContainerPort
            - "8079:8079"
        restart: always

    # # Notebook 
    jupyterlab:
        build:
            context: ./docker/jupyter
            dockerfile: Dockerfile.jupyter.stage
        image: jupyterlab-stage:1
        container_name: notebook-stage
        volumes:
            - ./:/home/jovyan/work/ModelOps
        networks: 
            - staging
        ports:
            - "8888:8888"
        depends_on: 
            - mlflow
        env_file: 
            - ./docker/jupyter/secrets.env

    # Tracking server
    mlflow:
        build:
            context: ./docker/mlflow
            dockerfile: Dockerfile.mlflow
        image: mlflow-stage:1
        container_name: tracking-server-stage
        volumes: 
            - mlflow:/mlflow
        ports:
            - "5000:5000"
        networks:
            - staging
        depends_on: 
            - postgres
            - minio
        env_file:
            - ./docker/mlflow/secrets.env

    # Tracking backend database
    postgres:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile.postgres
        image: postgres-stage:1
        container_name: tracking-database-stage
        volumes:
            - datapostgres:/var/lib/postgresql/data
        networks: 
            - staging
        ports: 
            - "5432:5432"
        restart: always

    # Tracking Artefact backend
    minio:
        build: 
            context: ./docker/minio
            dockerfile: Dockerfile.minio
        image: minio-stage:1
        container_name: tracking-artefact-stage
        volumes:
            - dataminio:/data
        networks: 
            - staging
        ports:
            - "9000:9000"
        env_file:
            - ./docker/minio/secrets.env
        command: server /data

volumes:
    datasql:
    mlflow:
    datapostgres:
    dataminio:

networks: 
    staging: